imports:
    - { resource: config.yml }

#framework:
#    cache:
#        system: cache.adapter.apcu

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  '%env(LOG_URL)%'
            level: debug
        console:
            type:  console

#Disable send email on Production
swiftmailer:
    disable_delivery:  true

twig:
    cache: false
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'

# EWZRecaptchaBundle
ewz_recaptcha:
    public_key:  6LetSH4UAAAAADHHSf0CxnXrUyEWEWye2miXC0s7
    private_key: 6LetSH4UAAAAACjZ-T0_rI5mz5pF7dWUyGSWTTNf
    locale_key:  %kernel.default_locale%
    locale_from_request: true